hpc_users_list:
  - username: hpcuser
    first_name: "HPC"
    last_name: "User"
    homedir: "/home/hpcuser"
    shell: "/bin/bash"
    groups:
      - hpc_users

  - username: hpcadmin
    first_name: "HPC"
    last_name: "Admin"
    homedir: "/home/hpcadmin"
    shell: "/bin/bash"
    groups:
      - hpc_users
      - hpc_admins

hpc_user_groups: 
  - hpc_users
  - hpc_admins

hpc_admin_group: hpc_admins
hpc_admin_sudo_rule: hpc-admins-all
