slurm_controller_host: "{{ slurm_controller_shortname }}"
slurm_compute_group: compute
slurm_packages:
  - "slurm-{{ slurm_package_version }}"
slurm_service_uid: 991
slurm_service_gid: 991
slurm_directories_root:
  - /etc/slurm
  - /var/spool/slurmd

slurm_directories_slurm:
  - /var/log/slurm
  - /var/spool/slurm
  - /var/spool/slurmctld

slurm_memory_reserve_mb: 256
slurm_config_path: "/etc/slurm/slurm.conf"
