plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

hostvars_prefix: aws_

filters:
  instance-state-name: [running]
  tag:ManagedBy: terraform
  tag:Project: HPCSlurmFreeIPA
  tag:AnsibleManaged: "true"

hostnames:
  - tag:NodeName

keyed_groups:
  - key: aws_ec2_tags.Role
    prefix: ""
    separator: ""

groups:
  freeipa_clients: "aws_ec2_tags.Role in ['controller', 'login', 'compute']"
  slurm_nodes: "aws_ec2_tags.Role in ['controller', 'login', 'compute']"

compose:
  ansible_host: aws_instance_id
  ansible_connection: '"amazon.aws.aws_ssm"'
  ansible_aws_ssm_region: aws_placement.region

strict: true
