---
- name: Install the Slurm controller
  ansible.builtin.dnf:
    name: "{{ slurm_controller_package }}"
    enablerepo: crb
    state: present

- name: Enable and start the Slurm controller
  ansible.builtin.systemd_service:
    name: "{{ slurm_controller_service }}"
    state: >-
      {{
        'restarted'
        if (slurm_common_configuration |
            default({'changed': false})).changed
        else 'started'
      }}
    enabled: true
