---

freeipa_server_packages:
  - firewalld
  - ipa-server
  - ipa-server-dns
  - rng-tools

freeipa_firewalld_services:
  - freeipa-4
  - dns

# The VPC resolver is at the VPC network address plus two.
freeipa_dns_forwarder: 10.20.0.2
freeipa_reverse_zone: 10.20.10.in-addr.arpa.
freeipa_dns_forward_test_name: aws.amazon.com

freeipa_server_state_file: /var/lib/ipa/sysrestore/sysrestore.state
freeipa_directory_server_instance: "{{ freeipa_realm | replace('.', '-') }}"
freeipa_directory_server_path: >-
  /etc/dirsrv/slapd-{{ freeipa_directory_server_instance }}
freeipa_pki_server_instance: pki-tomcat
freeipa_pki_server_path: /etc/pki/pki-tomcat
freeipa_partial_install_artifacts:
  - /root/.dogtag
  - /root/.ipa_cache
  - /root/ca-agent.p12
  - /root/cacert.p12
  - /root/ipa.csr
  - /etc/pki/pki-tomcat
  - /var/lib/pki/pki-tomcat
  - /var/log/pki/pki-tomcat
  - /etc/sysconfig/pki/tomcat/pki-tomcat
  - /etc/sysconfig/pki/tomcat
  - /etc/sysconfig/pki-tomcat
  - /etc/sysconfig/pki
  - /etc/systemd/system/pki-tomcatd.target.wants/pki-tomcatd@pki-tomcat.service
  - /etc/systemd/system/pki-tomcatd.target.wants/pki-tomcatd@{{ freeipa_pki_server_instance }}.service
  - /etc/systemd/system/pki-tomcatd@pki-tomcat.service.d
  - /etc/systemd/system/pki-tomcatd@{{ freeipa_pki_server_instance }}.service.d
  - /etc/systemd/system/multi-user.target.wants/pki-tomcatd@pki-tomcat.service
  - /etc/systemd/system/multi-user.target.wants/pki-tomcatd@{{ freeipa_pki_server_instance }}.service
  - /etc/systemd/system/pki-tomcatd.target.wants
  - /etc/dirsrv/slapd-{{ freeipa_directory_server_instance }}
  - /var/lib/dirsrv/slapd-{{ freeipa_directory_server_instance }}
  - /var/log/dirsrv/slapd-{{ freeipa_directory_server_instance }}
  - /var/run/dirsrv
